# Message Roles
# - System role: Used for instructions the model should use to answer a user question.
# - User role: Used for the user's query and any other content produced by the user
# - Assistant role: Used for content generated by the model.

# Chat message interfaces associated with each role
# - HumanMessage: A message sent from the perspective of the human, with the user role.
# - AIMessage: A message sent from the perspective of the AI that the human is interacting with, with the assistant role.
# - SystemMessage: A message setting the instructions the AI should follow, with the system role.
# - ChatMessage: A message allowing for arbitrary setting of role.

from langchain_ollama.chat_models import ChatOllama
from langchain_core.messages import HumanMessage

model = ChatOllama(model="granite4.1:3b")
prompt = [HumanMessage("What is the capital of France?")]

response = model.invoke(prompt)

print(response)